### ISSUE TITLE
Cannot read property 'environment' of undefined with latest commit.

### ISSUE THREAD

**Issue by ryanpcmcquen** [sn-extensions/components-api#1]
I'm using the latest commit in my [Org mode extension](https://github.com/ryanpcmcquen/standardnotes_org_mode_editor) and getting the following error:
https://cdn.rawgit.com/sn-extensions/components-api/b4d88cec7642266ddba8e7e9477ab21f9bd6d23b/dist/dist.js
```
Uncaught TypeError: Cannot read property 'environment' of undefined
    at ComponentManager.onReady (dist.js:88)
    at ComponentManager.handleMessage (dist.js:35)
    at ComponentManager.<anonymous> (dist.js:25)
```

**Comment by mobitar** [comment]
Sorry..I would use an earlier version. The latest commits are made for use in app version 2.1, which is still under development.

**Comment by ryanpcmcquen** [comment]
@mobitar, which is the right 'version'? I tried some earlier commits but they were having the same issue.

**Comment by mobitar** [comment]
Try 1.0.18

**Comment by ryanpcmcquen** [comment]
For reference, that would be this:
https://cdn.rawgit.com/sn-extensions/components-api/ab04ea47dcff97a01c536b4552756de2f672890a/dist/dist.js

**Comment by ryanpcmcquen** [comment]
That is working, would you mind updating this issue when I can upgrade to the latest commit?

**Comment by mobitar** [comment]
Will do!

On Jan 23, 2018, at 3:34 PM, Ryan P.C. McQuen <notifications@github.com>
wrote:

That is working, would you mind updating this issue when I can upgrade to
the latest commit?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/sn-extensions/components-api/issues/1#issuecomment-359938380>,
or mute the thread

**Comment by ryanpcmcquen** [comment]
@mobitar, is this stable again?

**Comment by mobitar** [comment]
Yup, with SN >= 2.1

**Comment by ryanpcmcquen** [comment]
Do you think following `master` would be OK?

**Comment by mobitar** [comment]
Yup should be ok
