### ISSUE TITLE
Having trouble installing extension

### ISSUE THREAD

**Issue by ryanpcmcquen** [sn-extensions/components-api#14]
Were there recent changes to this lib or to browsers, because I am getting weird errors when I try to install an extension:

```
Request error: index.js:1
    onreadystatechange React
Error downloading package details dist.js:655:17
TypeError: response is nulldist.js:4379:13
    downloadPackage dist.js:4379
    downloadPackageDetails dist.js:656
    onreadystatechange React
    <anonymous> self-hosted:1003
```

Related issue:
https://github.com/standardnotes/desktop/issues/602

**Comment by JaspalSuri** [comment]
Is this for every extension or just one extension?

**Comment by ryanpcmcquen** [comment]
So far I have only tested my own extension:

https://github.com/ryanpcmcquen/standardnotes_org_mode_editor

I will test another that uses the same version of this api.

**Comment by JaspalSuri** [comment]
Thank you for letting me know. I'll take note of the issues you've opened so that they will be reviewed after the refactor.

**Comment by ryanpcmcquen** [comment]
When is the refactor?

**Comment by JaspalSuri** [comment]
The dev team is currently working on it (it was started earlier this year, IIRC), so most of their attention is focused on that. I've assigned a task to myself with links to three of most recent issues that you've opened to bring it to their attention at some point after the refactor is complete.

**Comment by ryanpcmcquen** [comment]
@JaspalSuri, I think this may have been due to the CDN I was using (ghcdn and jsDelivr), I switched to gitcdn.xyz and everything seems to be working.
