### ISSUE TITLE
Did the install syntax change?

### ISSUE THREAD

**Issue by ryanpcmcquen** [sn-extensions/components-api#2]
I am attempting to install my Org mode editor using _Import extension_ in the new Extensions menu, and nothing is happening. I paste the install link (https://github.com/ryanpcmcquen/standardnotes_org_mode_editor#install-link) in the _Import extension_ box and hit enter, but the extension never gets installed.

**Comment by mobitar** [comment]
Steps have changed:
https://docs.standardnotes.org/extensions/publishing.html

**Comment by ryanpcmcquen** [comment]
How does this look?
https://ryanpcmcquen.org/standardnotes_org_mode_editor/org_mode.json

Wasn't quite sure what all the different URLs were supposed to be ...

**Comment by mobitar** [comment]
Check out the table "Key Descriptions" in https://docs.standardnotes.org/extensions/publishing.html.

`url` should be the hosted url of the web app.

**Comment by ryanpcmcquen** [comment]
OK, fixed the `url`, now I am getting a new error:
```
Request error: 
dist.min.js:6:1761
value/o.onreadystatechange<
https://app.standardnotes.org/extensions/extensions-manager/dist/dist.min.js:6:1761
Error downloading package details 
dist.min.js:1:4478
TypeError: n is null[Learn More]
dist.min.js:22:50807
value/<
https://app.standardnotes.org/extensions/extensions-manager/dist/dist.min.js:22:50807
value/<
https://app.standardnotes.org/extensions/extensions-manager/dist/dist.min.js:1:4529
value/o.onreadystatechange<
https://app.standardnotes.org/extensions/extensions-manager/dist/dist.min.js:6:1795
<anonymous> self-hosted:992:17
```

**Comment by ryanpcmcquen** [comment]
It was a CORS issue. Switching to https://gitcdn.link fixed it. Is there no longer a way to make an editor the default?

**Comment by mobitar** [comment]
You can, from the Editor menu.
