### ISSUE TITLE
Confused on the changes for mobile.

### ISSUE THREAD

**Issue by ryanpcmcquen** [sn-extensions/components-api#3]
I noticed the awesome update that added mobile support for editors, but it seems my Org mode editor is not getting any data:
https://github.com/ryanpcmcquen/standardnotes_org_mode_editor

I looked through the docs a bit, but I must be missing something. I am loading the latest version of this API:
https://min.gitcdn.link/repo/sn-extensions/components-api/master/dist/dist.js

Any ideas what I am doing incorrectly?

**Comment by mobitar** [comment]
Is your editor working on the latest version of the web/desktop app correctly? If you're using the latest version of the components-api, it should just work. It might be a caching issue. What's the link to your editor so I can test it out?

**Comment by mobitar** [comment]
Nm, found it. I installed your editor and it's working just fine for me on the iOS app. I think it may be a caching issue. Make sure you're on the latest version of the iOS/Android app (2.1.31+)

**Comment by ryanpcmcquen** [comment]
Interesting, I signed out and in on Android ... forgot to clear the cache, that was the fix! Thanks for the help, I love how Standard Notes is progressing.
